"use client"

export default function PrivacyP() {
  return (
    <div className="mx-auto px-[2rem] py-[10rem] md:px-[8rem]">
     
      <h1 className="text-[18px] md:text-[24px] text-bold text-blue-500 py-8 pt-[14rem]">Privacy Policy</h1>
      <p className="text-[18px] md:text-[24px] test-slate-300 py-6">Last updated: March 16, 2023</p>
      <p className="text-[16px] md:text-[19px] test-slate-300 py-6">This Privacy Policy outlines our practices regarding the gathering, utilization, and disclosure of your information when you use our Service. It also informs you about your privacy rights and how the law safeguards you.</p>
      <p className="text-[16px] md:text-[19px] test-slate-300 py-6">We utilize your personal data to supply and enhance our Service. By using the Service, you consent to the gathering and utilization of information as per this Privacy Policy.</p>
      <h2  className="text-[18px] md:text-[24px] test-slate-300 py-6">Interpretation and Definitions</h2>
      <h3  className="text-[18px] md:text-[24px] test-slate-300 py-6">Interpretation</h3>
      <p className="text-[16px] md:text-[19px] test-slate-300 py-6">The words of which the initial letter is capitalized carry meanings defined under the following conditions. These definitions hold the same meaning whether they appear in singular or plural form.</p>
      <h3  className="text-[18px] md:text-[24px] test-slate-300 py-6">Definitions</h3>
      <p  className="text-[18px] md:text-[24px] test-slate-300 py-6">For the purposes of this Privacy Policy:</p>
      <ul>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Account</strong> refers to a unique account created for you to access our Service or parts of our Service.</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Breederivier Budget Plumbers CC t/a Mr Plumber Worcester, 75 Durban Street, Worcester, Western Cape.</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Country</strong> refers to: South Africa</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Service</strong> refers to the Website.</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li  className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>Website</strong> refers to Mr Plumber, accessible https://www.neptuneplumbers.co.za</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>
      <h2  className="text-[18px] md:text-[24px] test-slate-300 py-6">Collecting and Using Your Personal Data</h2>
      <h3  className="text-[18px] md:text-[24px] test-slate-300 py-6">Types of Data Collected</h3>
      <h4  className="text-[18px] md:text-[24px] test-slate-300 py-6">Personal Data</h4>
      <p className="text-[18px] md:text-[24px] test-slate-300 py-2">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
      <ul>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">Email address</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">First name and last name</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">Phone number</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">Usage Data</li>
      </ul>
            <h2 className="text-[18px] md:text-[24px] test-slate-300 py-6">Use of Your Personal Data</h2>
      <p className="text-[18px] md:text-[24px] test-slate-300 py-2">The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2">To manage Your requests: To attend and manage Your requests to Us.</li>
      </ul>
      <p className="text-[18px] md:text-[24px] test-slate-300 py-2">We may share your personal information in the following situations:</p>
      <ul>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>For Business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>With Business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
        <li className="text-[18px] md:text-[24px] test-slate-300 py-2"><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
      </ul>
    </div>
  )
}
